//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabTextFinder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TabTextFinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Auto).
        /// </summary>
        internal static string FileEncoding_AutoDetect {
            get {
                return ResourceManager.GetString("FileEncoding_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        internal static string Filter_TextFile {
            get {
                return ResourceManager.GetString("Filter_TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon_find_white {
            get {
                object obj = ResourceManager.GetObject("Icon_find_white", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon_Find128 {
            get {
                object obj = ResourceManager.GetObject("Icon_Find128", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_asterisk {
            get {
                object obj = ResourceManager.GetObject("Img_asterisk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_clipboard {
            get {
                object obj = ResourceManager.GetObject("Img_clipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_clock {
            get {
                object obj = ResourceManager.GetObject("Img_clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_cross_button {
            get {
                object obj = ResourceManager.GetObject("Img_cross_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_database {
            get {
                object obj = ResourceManager.GetObject("Img_database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_document_search_result {
            get {
                object obj = ResourceManager.GetObject("Img_document_search_result", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_documents_stack {
            get {
                object obj = ResourceManager.GetObject("Img_documents_stack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_drive_download {
            get {
                object obj = ResourceManager.GetObject("Img_drive_download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_edit {
            get {
                object obj = ResourceManager.GetObject("Img_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_edit_lowercase {
            get {
                object obj = ResourceManager.GetObject("Img_edit_lowercase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_edit_rule {
            get {
                object obj = ResourceManager.GetObject("Img_edit_rule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_edit_shadow {
            get {
                object obj = ResourceManager.GetObject("Img_edit_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_editor {
            get {
                object obj = ResourceManager.GetObject("Img_editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_Find {
            get {
                object obj = ResourceManager.GetObject("Img_Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_folder__arrow {
            get {
                object obj = ResourceManager.GetObject("Img_folder__arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_folder_horizontal_open {
            get {
                object obj = ResourceManager.GetObject("Img_folder_horizontal_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_folders_stack {
            get {
                object obj = ResourceManager.GetObject("Img_folders_stack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_gear {
            get {
                object obj = ResourceManager.GetObject("Img_gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_information {
            get {
                object obj = ResourceManager.GetObject("Img_information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_keyboard {
            get {
                object obj = ResourceManager.GetObject("Img_keyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_locale {
            get {
                object obj = ResourceManager.GetObject("Img_locale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_magnifier {
            get {
                object obj = ResourceManager.GetObject("Img_magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_minus_white {
            get {
                object obj = ResourceManager.GetObject("Img_minus_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_plus_white {
            get {
                object obj = ResourceManager.GetObject("Img_plus_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_processor {
            get {
                object obj = ResourceManager.GetObject("Img_processor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_script_attribute_r {
            get {
                object obj = ResourceManager.GetObject("Img_script_attribute_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_spell_check {
            get {
                object obj = ResourceManager.GetObject("Img_spell_check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_split_horz {
            get {
                object obj = ResourceManager.GetObject("Img_split_horz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_split_vert {
            get {
                object obj = ResourceManager.GetObject("Img_split_vert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_system_monitor {
            get {
                object obj = ResourceManager.GetObject("Img_system_monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_ui_tab__minus {
            get {
                object obj = ResourceManager.GetObject("Img_ui_tab__minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Img_wrench_screwdriver {
            get {
                object obj = ResourceManager.GetObject("Img_wrench_screwdriver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string Label_Bytes {
            get {
                return ResourceManager.GetString("Label_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Esc&apos; to cancel.
        /// </summary>
        internal static string Label_CancelFind {
            get {
                return ResourceManager.GetString("Label_CancelFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chars.
        /// </summary>
        internal static string Label_Chars {
            get {
                return ResourceManager.GetString("Label_Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string Label_Column {
            get {
                return ResourceManager.GetString("Label_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Label_Content {
            get {
                return ResourceManager.GetString("Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string Label_FileName {
            get {
                return ResourceManager.GetString("Label_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Label_Files {
            get {
                return ResourceManager.GetString("Label_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Label_Line {
            get {
                return ResourceManager.GetString("Label_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string Label_Lines {
            get {
                return ResourceManager.GetString("Label_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample text
        ///
        ///When &quot;Lines&quot; option is enabled, a long single line of wordy and lengthy words will be wrapped into multiple lines. When &quot;Word&quot; options is also enabled, the wrapping will happen at word boundaries only.
        ///
        /// 1 space
        ///  2 spaces
        ///   3 spaces
        ///    4 spaces
        ///	1 tab character
        ///		2 tab characters
        ///        8 spaces
        ///         9 spaces
        ///          10 spaces
        ///           11 spaces
        ///            12 spaces
        ///			3 tab characters.
        /// </summary>
        internal static string Label_WrapSample {
            get {
                return ResourceManager.GetString("Label_WrapSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Menu_ChooseFont {
            get {
                return ResourceManager.GetString("Menu_ChooseFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all tabs.
        /// </summary>
        internal static string Menu_CloseAllTabs {
            get {
                return ResourceManager.GetString("Menu_CloseAllTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all tabs but this.
        /// </summary>
        internal static string Menu_CloseAllTabsButThis {
            get {
                return ResourceManager.GetString("Menu_CloseAllTabsButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this tab.
        /// </summary>
        internal static string Menu_CloseTab {
            get {
                return ResourceManager.GetString("Menu_CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy file path to clipboard.
        /// </summary>
        internal static string Menu_CopyPath {
            get {
                return ResourceManager.GetString("Menu_CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Menu_CopySelection {
            get {
                return ResourceManager.GetString("Menu_CopySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract result lines not matching selected text.
        /// </summary>
        internal static string Menu_ExcludeSelection {
            get {
                return ResourceManager.GetString("Menu_ExcludeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Menu_Export {
            get {
                return ResourceManager.GetString("Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with external editor.
        /// </summary>
        internal static string Menu_ExternalEditor {
            get {
                return ResourceManager.GetString("Menu_ExternalEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find selected text.
        /// </summary>
        internal static string Menu_FindSelection {
            get {
                return ResourceManager.GetString("Menu_FindSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find selected text in found files.
        /// </summary>
        internal static string Menu_FindSelectionInFound {
            get {
                return ResourceManager.GetString("Menu_FindSelectionInFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract result lines matching selected text.
        /// </summary>
        internal static string Menu_IncludeSelection {
            get {
                return ResourceManager.GetString("Menu_IncludeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder.
        /// </summary>
        internal static string Menu_OpenFolder {
            get {
                return ResourceManager.GetString("Menu_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string Menu_ShowProperty {
            get {
                return ResourceManager.GetString("Menu_ShowProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (File was modified).
        /// </summary>
        internal static string Mesg_FileModified {
            get {
                return ResourceManager.GetString("Mesg_FileModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Failed to open).
        /// </summary>
        internal static string Mesg_FileOpenFailed {
            get {
                return ResourceManager.GetString("Mesg_FileOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the following configuration file. Please rename or remove the configuration file. (The settings will be lost.).
        /// </summary>
        internal static string Mesg_InvalidSettings {
            get {
                return ResourceManager.GetString("Mesg_InvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files matched FILES / EXCLUDE pattern.
        /// </summary>
        internal static string Mesg_NoFilesMatched {
            get {
                return ResourceManager.GetString("Mesg_NoFilesMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text was not found.
        /// </summary>
        internal static string Mesg_TextNotFound {
            get {
                return ResourceManager.GetString("Mesg_TextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Search conditions
        /// FOLDERS : The root folder(s) to find target files (separated by a pipe &apos;|&apos;)
        /// FILES   : The filename / wildcard pattern(s) (separated by spaces)
        /// EXCLUDE : The filename / wildcard pattern(s) to exclude from search (separated by spaces)
        /// TEXT    : The keyword text to find
        ///
        ///
        ///* Example
        /// FOLDERS  [ C:\MyProject|D:\MyData ]
        /// FILES    [ *.xml *.h *.cpp        ]
        /// EXCLUDE  [ test.cpp               ]
        /// TEXT     [ class                  ]
        ///
        /// In this case,
        ///  1. For those files under C:\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Text_Help {
            get {
                return ResourceManager.GetString("Text_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surf Find.
        /// </summary>
        internal static string Title_Application {
            get {
                return ResourceManager.GetString("Title_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of searched bytes.
        /// </summary>
        internal static string ToolTip_Bytes {
            get {
                return ResourceManager.GetString("ToolTip_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        internal static string ToolTip_Case {
            get {
                return ResourceManager.GetString("ToolTip_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of searched chars.
        /// </summary>
        internal static string ToolTip_Chars {
            get {
                return ResourceManager.GetString("ToolTip_Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time to find.
        /// </summary>
        internal static string ToolTip_Elapsed {
            get {
                return ResourceManager.GetString("ToolTip_Elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the file encoding used to read files.
        /// </summary>
        internal static string ToolTip_Encoding {
            get {
                return ResourceManager.GetString("ToolTip_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filenames / wild card patterns to exclude from search (separated by spaces).
        /// </summary>
        internal static string ToolTip_ExcludeFile {
            get {
                return ResourceManager.GetString("ToolTip_ExcludeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filenames / wild card patterns to search for (separated by spaces).
        /// </summary>
        internal static string ToolTip_File {
            get {
                return ResourceManager.GetString("ToolTip_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total numbers of matched files / searched files.
        /// </summary>
        internal static string ToolTip_Files {
            get {
                return ResourceManager.GetString("ToolTip_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract non-matched lines from the result lines on the current tab (Ctrl + Enter).
        /// </summary>
        internal static string ToolTip_FindExcl {
            get {
                return ResourceManager.GetString("ToolTip_FindExcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the text in the found files on the current tab (Shift + Ctrl +Enter).
        /// </summary>
        internal static string ToolTip_FindFound {
            get {
                return ResourceManager.GetString("ToolTip_FindFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract matched lines from the result lines on the current tab (Shift + Enter).
        /// </summary>
        internal static string ToolTip_FindIncl {
            get {
                return ResourceManager.GetString("ToolTip_FindIncl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total numbers of matched lines / searched lines.
        /// </summary>
        internal static string ToolTip_Lines {
            get {
                return ResourceManager.GetString("ToolTip_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GC memory size : click here to invoke garbage collection.
        /// </summary>
        internal static string ToolTip_Memory {
            get {
                return ResourceManager.GetString("ToolTip_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search options used.
        /// </summary>
        internal static string ToolTip_Options {
            get {
                return ResourceManager.GetString("ToolTip_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive search into sub folders.
        /// </summary>
        internal static string ToolTip_Recursive {
            get {
                return ResourceManager.GetString("ToolTip_Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use regular expression.
        /// </summary>
        internal static string ToolTip_Regx {
            get {
                return ResourceManager.GetString("ToolTip_Regx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root folders to start a search (separated by a pipe &apos;|&apos;).
        /// </summary>
        internal static string ToolTip_Root {
            get {
                return ResourceManager.GetString("ToolTip_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find it! (Enter).
        /// </summary>
        internal static string ToolTip_StartFind {
            get {
                return ResourceManager.GetString("ToolTip_StartFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword text to find.
        /// </summary>
        internal static string ToolTip_Text {
            get {
                return ResourceManager.GetString("ToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match whole word.
        /// </summary>
        internal static string ToolTip_Word {
            get {
                return ResourceManager.GetString("ToolTip_Word", resourceCulture);
            }
        }
    }
}
